### ISSUE TITLE
SCAF-US-15 測試6 模糊搜尋

### ISSUE THREAD

**Issue by jteng2127** [ScafTeam/scaf-team#9]
模糊搜尋不是顯示相似的相關問題，而是做近似字串比對與錯字處理，例如
「怎麼修改我的個人資料」會找到「個人資料/修改個人資料」的頁面
fro, fom, frmo, fron, form 都可以找到 from

另外也可以在搜尋文章時對文章內容比對，例如搜尋某個錯誤訊息可以找到哪個文章有提及該錯誤訊息的解決方法。

**Comment by jimmyhealer** [comment]
https://www.algolia.com/
